### ISSUE TITLE
Coding error detected, it must be fixed by a programmer: Invalid property requested, or the property does not has a default value.

### ISSUE THREAD

**Issue by empereira** [damalis/full-stack-apache2-moodle-for-everyone-with-docker-compose#1]
hello @damalis ,

I up your Docker stack, no apparent errors. When accessing my moodledev... during its installation, I encountered this error::

![image](https://github.com/user-attachments/assets/8b12db73-bf46-4099-9242-80d83def8038)

Clicking on “continue” gives me the same error.

I enabled debugging in config.php and it showed the errors:
```
10.20.2.5 -  21/Oct/2024:13:43:50 -0300 "POST /moodle/lib/ajax/service-nologin.php" 200
10.20.2.5 -  21/Oct/2024:13:44:04 -0300 "GET /moodle/admin/index.php" 303
10.20.2.5 -  21/Oct/2024:13:44:05 -0300 "GET /moodle/admin/index.php" 303
NOTICE: PHP message: Default exception handler: Coding error detected, it must be fixed by a programmer: Invalid property requested, or the property does not has a default value. Debug: 
Error code: codingerror
* line 924 of /lib/classes/user.php: coding_exception thrown
* line 301 of /user/editlib.php: call to core_user::get_property_default()
* line 153 of /user/editadvanced_form.php: call to useredit_shared_definition()
* line 217 of /lib/formslib.php: call to user_editadvanced_form->definition()
* line 155 of /user/editadvanced.php: call to moodleform->__construct()
10.20.2.5 -  21/Oct/2024:13:44:05 -0300 "GET /moodle/user/editadvanced.php" 200
10.20.2.5 -  21/Oct/2024:13:44:06 -0300 "GET /moodle/lib/javascript.php" 200
10.20.2.5 -  21/Oct/2024:13:44:06 -0300 "GET /moodle/lib/javascript.php" 200
10.20.2.5 -  21/Oct/2024:13:44:06 -0300 "GET /moodle/lib/javascript.php" 200
NOTICE: PHP message: Default exception handler: Coding error detected, it must be fixed by a programmer: Invalid property requested, or the property does not has a default value. Debug: 
Error code: codingerror
* line 924 of /lib/classes/user.php: coding_exception thrown
* line 301 of /user/editlib.php: call to core_user::get_property_default()
* line 153 of /user/editadvanced_form.php: call to useredit_shared_definition()
* line 217 of /lib/formslib.php: call to user_editadvanced_form->definition()
* line 155 of /user/editadvanced.php: call to moodleform->__construct()
10.20.2.5 -  21/Oct/2024:13:44:06 -0300 "GET /moodle/user/editadvanced.php" 200
10.20.2.5 -  21/Oct/2024:13:44:06 -0300 "GET /moodle/theme/styles.php" 200
```

Any idea what it could be?

**Comment by damalis** [comment]
hello @empereira 

did you look at this page [https://docs.moodle.org/405/en/error/debug/codingerror](https://docs.moodle.org/405/en/error/debug/codingerror)

**Comment by empereira** [comment]
> hello @empereira
> 
> did you look at this page https://docs.moodle.org/405/en/error/debug/codingerror

@damalis ,

Yes, I read it! I tried purging the cache, but it didn't work. I checked the suggested topic, but the last post is from 2017. There have been many updates since then.

But since I just made a git clone and then ran install.sh, maybe it's a problem with the stack settings?

Any ideas on how to fix it?

**Comment by damalis** [comment]
@empereira 

maybe, solution is this page [https://moodle.org/mod/forum/discuss.php?d=418095](https://moodle.org/mod/forum/discuss.php?d=418095).

It isn't problem the stack settings, because does install only moodle.

**Comment by empereira** [comment]
I ended up leaving it alone and installing the bitnami stack.

I'll try again some other time.

Thanks for your help!
